---
- name: Deploy nginx container with external index.html
  hosts: demo
  become: yes
  collections:
    - community.docker

  vars:
    host_dir: /home/web-og/nginx_demo
    index_content: |
      <!doctype html>
      <html>
      <head><meta charset="utf-8"><title>Demo</title></head>
      <body><h1>Привет от Nginx в контейнере</h1></body>
      </html>
    nginx_conf: |
      server {
          listen 80;
          root /usr/share/nginx/html;

          location / {
              index index.html index.htm;
              try_files $uri $uri/ /index.html =404;
          }

          error_page 404 /index.html;
          location = /404 {
              return 404;
          }
      }

  tasks:
    - name: Ensure host directory exists
      file:
        path: "{{ host_dir }}"
        state: directory
        owner: web-og
        mode: '0755'

    - name: Create index.html on host to be mounted
      copy:
        content: "{{ index_content }}"
        dest: "{{ host_dir }}/index.html"
        owner: web-og
        mode: '0644'

    - name: Create nginx default.conf on host
      copy:
        content: "{{ nginx_conf }}"
        dest: "{{ host_dir }}/default.conf"
        owner: web-og
        mode: '0644'

    - name: Pull nginx image
      community.docker.docker_image:
        name: nginx:latest
        source: pull

    - name: Ensure nginx container is running
      community.docker.docker_container:
        name: nginx_demo
        image: nginx:latest
        state: started
        restart_policy: always
        published_ports:
          - "8081:80"
        volumes:
          - "{{ host_dir }}/index.html:/usr/share/nginx/html/index.html:ro"
          - "{{ host_dir }}/default.conf:/etc/nginx/conf.d/default.conf:ro"