version: '3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example_password
    ports:
      - "5432:5432"
    networks:
      - my-pg-network

networks:
  my-pg-network:
    driver: bridge
