version: "3.9"

services:
  nginx:
    image: nginx:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
      - source: index_html
        target: /usr/share/nginx/html/index.html
    networks:
      - my_overlay

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.pg==true
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_overlay

configs:
  nginx_conf:
    file: ./nginx.conf
  index_html:
    file: ./index.html

networks:
  my_overlay:
    driver: overlay

volumes:
  pgdata:
    driver: local
